/*Showing switch cases for buttons */

package com.example.appp11;

import android.os.Bundle;
import android.app.Activity;
import android.view.Menu;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;

public class MainActivity11 extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main_activity11);

    }
        public void click(View v)//function onclicking where we can get its id and then apply switch case to to ids generated by the v.getid() function 
        {
        	ImageView im=(ImageView)findViewById(R.id.imageView1);	
        switch(v.getId())
        {
        case R.id.button1:
        
        	im.setImageResource(R.drawable.abc1);
        break;
        case R.id.button2:
        
        	im.setImageResource(R.drawable.abc2);
        break;
        }
    }
    


    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.main_activity11, menu);
        return true;
    }
    
}
